### ISSUE TITLE
[tck, _] instead of tck, u

### ISSUE THREAD

**Issue by oliver-schumann** [kaouacherif/Python-B-spline-examples#1]
Hi thanks for the useful code. Especially answer B is what you normally need!
But here, I would change the return of splrep to 
[tck, _] = ...

Pycharm gives otherwise a warning because of the return values to unpack and the double definition of u.
Thank you!

**Comment by kawache** [comment]
@trickster-117 you can open a PR to fix it, thank you

**Comment by antun** [comment]
Thanks for sharing this the original examples @kawache  and the correction @oliver-schumann !

I went ahead and submitted a PR that includes Oliver's fix: https://github.com/kawache/Python-B-spline-examples/pull/2

(Took me a bit of guessing before I looked at this open issue!)
